# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
defaults: &defaults
  #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #### expecting it in the form of
  ####   /go/src/github.com/circleci/go-tool
  ####   /go/src/bitbucket.org/circleci/go-tool
  working_directory: /go/src/github.com/dolab/httptesting
default_steps: &default_steps
  steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: go get -v golang.org/x/net/websocket
    - run: go get -v github.com/golib/assert
    - run: go get -v github.com/buger/jsonparser
    - run: go test -v
    - run: go test -v -race
jobs:
  go1.6:
    <<: *defaults
    docker:
      # specify the version
      - image: golang:1.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    <<: *default_steps
  go1.8:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    <<: *default_steps
  go1.11:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    <<: *default_steps
  go:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    <<: *default_steps

workflows:
  version: 2
  build_and_test:
    jobs:
      #- go1.6
      - go1.8
      - go1.11
      - go